DROP TABLE SHEEBA.EFTSECUSR CASCADE CONSTRAINTS;

CREATE TABLE EFTSECUSR
(
  USRID        VARCHAR2(20 BYTE),
  UPWD         VARCHAR2(20 BYTE),
  GROUPS       VARCHAR2(20 BYTE),
  PROFILE_PIC  BLOB
);

CREATE OR REPLACE SYNONYM EFTSECUSR FOR EFTSECUSR;

SET DEFINE OFF;
Insert into EFTSECUSR
   (USRID, UPWD, GROUPS)
 Values
   ('admin', 'admin', 'ADMIN');
Insert into EFTSECUSR
   (USRID, UPWD, GROUPS)
 Values
   ('doctor', 'admin', 'DOCTOR');
Insert into EFTSECUSR
   (USRID, UPWD, GROUPS)
 Values
   ('patient', 'admin', 'PATIENT');
COMMIT;
